### PR TITLE
Upgrade deps

### PR DESCRIPTION
**Pull request by SimenB**
This will dedupe better

### CODE REVIEW

**Comment by SimenB** [comment]
Have you considered using `^`? Now that npm@5 by default uses lockfiles, IMO it should be up to consumers to lock down dependencies if they want to

**Comment by SimenB** [comment]
Could you do a patch release of this?

**Comment by kesla** [comment]
Hey, I got sidetracked. Will push a few updates (going to `^` as you suggested above) and then push a patch release!

**Comment by kesla** [comment]
done! Thanks for the help.

**Comment by SimenB** [comment]
Thanks!

**Pull request merged**
