### PR TITLE
include sys/uio.h in check headers

### PR DESCRIPTION
**Pull request by peakji**
Fixed a configuration error in snappy: https://github.com/google/snappy/pull/32

Without checking `sys/uio.h`, `ac_cv_have_sys_uio_h` will always be **0** @ [snappy-stubs-public.h.in#L47](https://github.com/google/snappy/blob/master/snappy-stubs-public.h.in#L47)

### CODE REVIEW

**Comment by kesla** [comment]
@peakji Shouldn't this be fixed in the core snappy? Seem odd to me to patch snappy like this in here.

**Comment by peakji** [comment]
It will be identical once https://github.com/google/snappy/pull/32 got merged. 😜 Let's wait core snappy.

**Comment by mbroadst** [comment]
this will be superseded by #152

**Comment by kesla** [comment]
closing since #152 was merged.

**Pull request closed without merging**
