### PR TITLE
add windows CI

### PR DESCRIPTION
**Pull request by hex7c0**
add windows badge

### CODE REVIEW

**Comment by kesla** [comment]
Awesome!

**Comment by hex7c0** [comment]
there is an issue with appveyor webhook, doesn't refresh the test with new commit
(maybe because I'm not the owner)

try with your account

**Comment by kesla** [comment]
Hey @hex7c0 done in #41

**Comment by hex7c0** [comment]
great job! I'll delete project on my appveyor

p.s. look at next commit
I'll open an issue later

**Pull request merged**
