### PR TITLE
pangyp deprecated, upgrade to node-gyp@3+

### PR DESCRIPTION
**Pull request by speier**

### CODE REVIEW

**Comment by kesla** [comment]
@speier thanks for this! Weirdly enough travis fails on iojs@3 - I'm wondering what that's about... Perhaps it would make sense to add node@4 to `.travis.yml` (if it's available)

**Comment by kkoopa** [comment]
It's available and all works fine.

https://travis-ci.org/nodejs/nan/builds/79465370
https://github.com/nodejs/nan/blob/master/.travis.yml

**Comment by kkoopa** [comment]
You might be getting tripped up by the global node-gyp installed from iojs-3 taking precedence over the local one which is supposed to be used. https://github.com/nodejs/nan/blob/master/.travis.yml#L30

**Comment by stryju** [comment]
@speier mind fixing `.travis.yml` in this PR?

**Comment by stryju** [comment]
closed? what happened?

**Comment by kkoopa** [comment]
You need to use g++-4.8 and upgrade npm for node 0.8.

**Pull request closed without merging**
