### PR TITLE
Restyling

### PR DESCRIPTION
**Pull request by hex7c0**
- Mocha BDD
- export c++ binding
- update bindings@1.2.1

### CODE REVIEW

**Comment by kesla** [comment]
why oh why test from tape to mocha? I use tap pretty much everywhere and love it.

Rest of it looks great!

**Comment by hex7c0** [comment]
for test-suite:
mocha is great for BDD and code-coverage

just a suggestion :)

**Comment by kesla** [comment]
@hex7c0  Hey, this was a little bit too big of a PR to be accepted at the time and now it's gotten stale so I'm going to close this.

If there's part of this that you still want in (check input on `isValidCompressed` or adding the `.bindings`-stuff) then I suggest open new PRs instead and for larger stuff (like changing the test framework) it'll make sense to discuss in issues first.

**Comment by hex7c0** [comment]
no problem :+1: 
I'll open new PR for check input

**Pull request closed without merging**
